name: SamplePipeline

on: 
  push:
    branches: [main]
jobs: 
  lintTest:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - name: Clone Repository
          uses: actions/checkout@v2

        - name: Install Dependencies
          run: |
            echo "Installing Dependencies..."
            npm install
        - name: Running Linting 
          run: |
            echo  "Running Linting test..."
            npm run lint
          env:  
            CI: true
  runPrcoess: 
      name: RunProcess in 5 sec
      runs-on: ubuntu-latest
      steps:
        - name: Run The RunProcess
          run: |
            echo "Running the process..."
            sleep 5s;
            echo  "Running the process...2"
            sleep 5s;
            echo "Running the process...3"

        
      